site_name: "Rat Rig - V-Minion"
site_url: https://v-minion.ratrig.com/
site_author: "Rat Rig"
site_description: "The V-Minion is a premium DIY kit for a small form factor Cartesian 3D printer, with big features."
edit_uri: ""

copyright: Copyright &copy; 2021 Rat Rig
extra:
  generator: false

repo_name: V-Minion
repo_url: https://github.com/Rat-Rig/V-Minion

docs_dir: docs/src
site_dir: site
theme:
  logo: assets/logo_rat_medium.png
  favicon: assets/logo_rat_small.png
  language: en
  name: material
  custom_dir: docs/overrides
  palette:
    scheme: default
    primary: rat_rig
    accent: rat_rig_alt
  features:
    # - navigation.instant
    - navigation.tabs.sticky
    - navigation.tabs
    - navigation.tracking
    - search.suggest
    - search.highlight

plugins:
  - search
  - awesome-pages
  - ratrig-productpages-plugin:
      product_name: "V-Minion"
      order_url: https://www.ratrig.com/v-minion.html
      cad_url: https://cad.onshape.com/documents/15a2d417ffe6419f44f2b12e/w/92c82e3b2fbb251796f47d96/e/92a0ed9a1042e4b97032f956
      splash_video_url: https://www.youtube.com/embed/QXFAqerE9ws
      facebook_url: https://www.facebook.com/groups/ratrig3dprintercommunity
      discord_url: https://discord.gg/D62e8XNeYa

extra_css:
  - css/extra.css

extra_javascript:
  - https://cdn.scaleflex.it/plugins/js-cloudimage-360-view/2.4.1/js-cloudimage-360-view.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/extra.js

markdown_extensions:
  - abbr
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
      toc_depth: 1

nav:
    - index.md
    - Order: https://www.ratrig.com/v-minion.html" target="_blank
    - bom.md
    - printed_parts.md
    - electronics.md
    - firmware.md
    - Build Guide: https://ratrig.dozuki.com/c/02._Rat_Rig_V-Minion" target="_blank
    - contribution.md
    - community.md
    # - Gallery: https://www.ratrig.com/" target="_blank
    - videos.md
    - Contact: mailto:info@ratrig.com
